services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./funny/videos:/app/videos
      - ./funny/queue:/app/queue
      - ./funny/instance:/app/instance
    environment:
      - FLASK_ENV=production
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=CHANGETHISPASSWORDNOW
    restart: unless-stopped
